name: update-code

on:
  workflow_dispatch: {}
  push:
    #branches: [master, main] # TODO: uncomment
    paths: [code/**, .github/workflows/update-code.yml]

concurrency:
  group: ${{ github.ref }}-code
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_DEPLOY_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: code-tarampamp-am
          directory: .
          workingDirectory: ./code
          branch: main # aka CF "production" environment
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
